metricbeat.modules:
- module: logstash-xpack
  xpack.enabled: true

- module: elasticsearch-xpack
  xpack.enabled: true

- module: logstash
  enabled: true
  period: 15s
  hosts: ["http://logstash:9600"]
  xpack.enabled: true

- module: elasticsearch
  enabled: true
  period: 15s
  hosts: ["http://elasticsearch:9200"]
  xpack.enabled: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]